---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/nexo-app
    - /bin/bash -c "cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction 2>&1"
    - /bin/bash -c "cd $DEPLOYPATH && php artisan config:clear 2>&1"
    - /bin/bash -c "cd $DEPLOYPATH && php artisan config:cache 2>&1"
    - /bin/bash -c "cd $DEPLOYPATH && php artisan route:cache 2>&1"
    - /bin/bash -c "cd $DEPLOYPATH && php artisan view:clear 2>&1"
    - /bin/bash -c "cd $DEPLOYPATH && php artisan migrate --force 2>&1"
    - /bin/bash -c "cd $DEPLOYPATH && php artisan storage:link 2>&1"
